config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tasks do
    post :toggle, on: :member
  end
  # post "tasks/:id/toggle", to: "tasks#toggle"
  # Defines the root path route ("/")
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      format.html do
        if @task.save
          flash[:success] = "Post saved successfully."
          redirect_to tasks_url
        else
          flash[:error] = @task.errors.full_messages.to_sentence
          render :new
        end
      end
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html do
        if @task.update(task_params)
          flash[:success] = "Task was successfully updated"
          redirect_to tasks_url
        else
          flash[:error] = @task.errors.full_messages.to_sentence
          render :edit
        end
      end
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:success] = "Task was successfully deleted"
    redirect_to tasks_url
  end

  def toggle
    @task = Task.find(params[:id])
    @task.update(completed: params[:completed], completed_at: params[:completed_at])

    render json: { message: "Success" }
  end

  private

  def task_params
    params.require(:task).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To-Do List (Hotwire)</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>
  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <% flash.each do |type, msg| %>
        <% if type == "error"%>
          <div class="min-w-0 max-w-max py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block">
            <%= msg %>
          </div>
        <% elsif type == "success" %>
          <div class="min-w-0 max-w-max py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block">
            <%= msg %>
          </div>
        <% else %>
          <div class="min-w-0 max-w-max py-2 px-3 bg-yellow-50 mb-5 text-yellow-500 font-medium rounded-lg inline-block">
            <%= msg %>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "flex align-center mb-7") do |form| %>
  <div class="flex flex-wrap mb-5">
    <%= form.text_field :description, placeholder: "Add a new task", class: "min-w-0 w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
    <%= form.submit "Save", class: "btn w-24 py-2 ml-2 bg-blue-600 text-white" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<turbo-frame id="<%= dom_id task %>">
  <div class="flex flex-wrap items-center mr-5">
    <p class="text-xs text-gray-500 w-20 mr-5"><%= task.completed_at %></p>
    <%= form_with(model: task, class:"text-lg inline-block my-3 w-96") do |form| %>
      <%= form.check_box :completed,
                       data: {
                         id: task.id,
                         completed_at: DateTime.now.strftime("%Y-%m-%d %I:%M:%S"),
                         action: "tasks#toggle"
                       },
                       class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500" %>
      <%= task.description %>
    <% end %>
    <%= link_to "Edit", edit_task_path(task),
              class: "btn bg-gray-100"
  %>
    <div class="inline-block ml-2">
      <%= button_to "Delete", task_path(task),
                  method: :delete,
                  data: { "turbo-frame": "_top" },
                  class: "btn bg-red-100" %>
    </div>
  </div>
</turbo-frame>

app/views/tasks/edit.html.erb
<div class="said">
  <h1 class="font-bold text-2xl mb-3">Edit task</h1>
  <turbo-frame id="<%= dom_id @task %>">
    <%= render "form", task: @task %>
    <%= link_to "Back", tasks_path, class: "btn mb-3 bg-gray-100" %>
  </turbo-frame>
</div>

app/views/tasks/index.html.erb
<h1 class="font-bold text-2xl">Task Manager</h1>
<div class="mt-4">
  <%= render "form", task: @task %>
</div>
<div id="tasks">
  <h1 class="font-bold text-lg mb-7">Tasks</h1>
  <div class="px-5" data-controller="tasks">
    <%= render @tasks %>
  </div>
</div>